device: cuda:0

# transition_data: /data/AlexPleava/outputs/dstl_pretrain_rl/BoxPlace-Direct-v0/1/2026-02-10_00-51-50/data/training.h5
# teacher_config: /data/AlexPleava/outputs/dstl_pretrain_rl/BoxPlace-Direct-v0/1/2026-02-10_00-51-50/params/agent.yaml
# teacher_model: /data/AlexPleava/outputs/dstl_pretrain_rl/BoxPlace-Direct-v0/1/2026-02-10_00-51-50/models/final.pt
transition_data: /data/AlexPleava/outputs/dstl_pretrain_rl/BoxPlace-Direct-v0/1/2026-02-18_20-01-55/data/training.h5
teacher_config: /data/AlexPleava/outputs/dstl_pretrain_rl/BoxPlace-Direct-v0/1/2026-02-18_20-01-55/params/agent.yaml
teacher_model: /data/AlexPleava/outputs/dstl_pretrain_rl/BoxPlace-Direct-v0/1/2026-02-18_20-01-55/models/final.pt

student_encoder_checkpoint: /data/AlexPleava/outputs/students/student_encoder_19.pt
student_dynamics_checkpoint: /data/AlexPleava/outputs/students/student_dynamics_19.pt
student_reward_checkpoint: /data/AlexPleava/outputs/students/student_reward_19.pt

action_dim: 7
teacher_latent_dim: 512
student_latent_dim: 20

epochs: 20

encoder_hidden_dim: 50
encoder_shared_hidden_layers: 3

dynamics_hidden_dim: 50
dynamics_shared_hidden_layers: 3

reward_hidden_dim: 50
reward_shared_hidden_layers: 3

learning_rate: 1e-4
batch_size: 128
beta: 1
validation_interval: 0.1

save_path: /data/AlexPleava/outputs/students

